### ISSUE TITLE
Error: Cannot find module 'mustache' (line:16)

### ISSUE THREAD

**Issue by CanadaTesla** [nekloth/node-red-contrib-netatmo-thermostat#4]
Helo all.
I Have this messege "Error: Cannot find module 'mustache' (line:17)" in Node Red with Raspberry Pi b+.
Any idea.
Thanks for your help.
Regards

**Comment by CanadaTesla** [comment]
Solution:
nmp install fixed mustache

**Comment by CanadaTesla** [comment]
thanks

**Comment by Sherco49** [comment]
Hi
i npm install -g mustache in my .node-red directory, but still have the same warning problem (in Windows 10)
could you precise the command line ?

**Comment by Sherco49** [comment]
i wrote "npm install fixed mustache", and this resolve my warnings ( didn't trust teh word "fixed"
Sorry for this
